language: java
jdk:
  - oraclejdk11
cache:
  directories:
    - .autoconf
    - $HOME/.m2
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
  - chmod +x mvnw
script: bash ./deploy.sh